export const cities = [
    {label: "Rio de Janeiro"},
    {label: "São Paulo"},
    {label: "Fortaleza"},
    {label: "Belo Horizonte"},
    {label: "Rio Branco"},
    {label: "Macapá"},
    {label: "Manaus"},
    {label: "Belém"},
    {label: "Porto Velho"},
    {label: "Boa Vista"},
    {label: "Palmas"},
    {label: "Maceió"},
    {label: "Salvador"},
    {label: "São Luís"},
    {label: "João Pessoa"},
    {label: "Recife"},
    {label: "Teresina"},
    {label: "Natal"},
    {label: "Aracaju"},
    {label: "Brasília"},
    {label: "Goiânia"},
    {label: "Cuiabá"},
    {label: "Campo Grande"},
    {label: "Vitória"},
    {label: "Curitiba"},
    {label: "Florianópolis"},
    {label: "Porto Alegre"},
]