//Lista de Especialidades
export const specialty = [
    {label : 'Ginecologista'},
    {label : 'Psiquiatra'},
    {label : 'Psicólogo'},
    {label : 'Dermatologista'},
    {label : 'Ortopedista Traumatologista'},
    {label : 'Endocrinologista'},
    {label : 'Oftalmologista'},
    {label : 'Médico Clínico Geral'},
    {label : 'Cardiologista'},
    {label : 'Urologista'},
    {label : 'Dentista'},
    {label : 'Otorrino'},
    {label : 'Cirurgião Plástico'},
    {label : 'Neurologista'},
    {label : 'Cirurgião Geral'},
    {label : 'Gastroenterologista'},
    {label : 'Neurocirurgião'},
    {label : 'Generalista'},
    {label : 'Nutricionista'},
    {label : 'Angiologista'},
    {label : 'Cirurgião Do Aparelho Digestivo'},
    {label : 'Reumatologista'},
    {label : 'Coloproctologista'},
    {label : 'Alergista'},
    {label : 'Pneumologista'},
    {label : 'Cirurgião Vascular'},
    {label : 'Mastologista'},
    {label : 'Hematologista'},
    {label : 'Oncologista'},
    {label : 'Cirurgião Buco-Maxilo-Facial'},
    {label : 'Nefrologista'},
    {label : 'Geriatra'},
    {label : 'Psicanalista'},
    {label : 'Infectologista'},
    {label : 'Nutrólogo'},
    {label : 'Fisioterapeuta'},
    {label : 'Cirurgião de Cabeça e Pescoço'},
    {label : 'Neurologista Pediátrico'},
    {label : 'Endoscopista'},
    {label : 'Homeopata'},
    {label : 'Fonoaudiólogo'},
    {label : 'Médico Acunputurista'},
    {label : 'Radiologista'},
    {label : 'Cirurgião Da Mão'},
    {label : 'Anestesiologista'},
    {label : 'Endocrinologista Pediátrico'},
    {label : 'Médico Do Trabalho'},
    {label : 'Cirurgião Pediátrico'},
    {label : 'Cirurgião Cardiovascular'},
    {label : 'Médico de Família'},
    {label : 'Médico do Esporte'},
    {label : 'Cirurgião Torácito'},
    {label : 'Cirurgião Oncológico'},
    {label : 'Terapeuta Complementar'},
    {label : 'Pneumologista Pediátrico'},
    {label : 'Geneticista'},
    {label : 'Intensivista'},
    {label : 'Especialista em Dor'},
    {label : 'Médico do Sono'},
    {label : 'Especialista em Médicina Física'},
    {label : 'Quiropraxista'},
    {label : 'Especialista em Médicina Estética'},
    {label : 'Gastroenterologista Pediátrico'},
    {label : 'NeuroFisiologista'},
    {label : 'Médico de Tráfego'},
    {label : 'Internista'},
    {label : 'Psicopedagogo'},
    {label : 'Especialista Em Diagnóstico Por Imagem'},
    {label : 'Anátomopatologista'},
    {label : 'Osteopata'},
    {label : 'Podologista'},
    {label : 'Sexólogo'},
    {label : 'Patologista Clínico'},
    {label : 'Especialista Em Clínica Médica'},
    {label : 'Terapeuta Ocupacional'},
    {label : 'Alergista Pediátrico'},
    {label : 'Cirurgião Cranio-Maxilo-Facil'},
    {label : 'Médico Perito'},
    {label : 'Hepatologista'},
    {label : 'Nefrologista Pediátrico'},
    {label : 'Radioterapeuta'},
    {label : 'Enfermeiro'},
    {label : 'Especialista Em Administração Em Saúde'},
    {label : 'Infectologista Pediátrico'},
    {label : 'Ortodontista'},
    {label : 'Reumatologista Pediátrico'},
    {label : 'Especialista Em Medicina Nuclear'},
    {label : 'Especialista Em Medicina Preventiva'},
    {label : 'Hematologista Pediátrico'},
    {label : 'Especialista Em Reproducao Humana'},
    {label : 'Especialista Em Biomedicina'},
    {label : 'Médico de Emergência'},
    {label : 'Odontopediatra'},
    {label : 'Médico Hiperbarista'},
    {label : 'Especialista Em Medicina Do Adolescente'},
    {label : 'Educador Físico'},
    {label : 'Especialista Em Harmonização Orofacial'},
    {label : 'Médico Citopatologista'}
]

